version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: marhba_postgres

    restart: always

    environment:
      POSTGRES_DB: marhba_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: